config/routes.rb
Rails.application.routes.draw do

  get 'sign_up' => 'users#new', :as => 'sign_up'
  get "users/:id" => "users#show", as: "user_show"
  get "users/:id/api_token" => "users#api_token", as: "user_api_token"
  resources :users

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: [:new, :create, :destroy]

  resources :entries do
    resources :comments, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1, path: "" do
      resources :users, except: [:new, :edit]
      resources :entries, except: [:index, :new, :edit] do
        resources :comments, shallow: true
      end
    end
  end

  get 'home/index'

  root 'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  before_create :set_date

  belongs_to :entry

  validates :name, presence: true, length: { minimum: 1, maximum: 50 }
  validates :description, presence: true, length: { minimum: 1, maximum: 1024 }

  def set_date
    self.post_date = Time.now
  end
end

app/controllers/api/v1/comments_controller.rb
class API::V1::CommentsController < API::V1::BaseController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_entry, only: [:create]
  before_action only: [:update, :destroy] do
    authorize(:comment, @comment.id)
  end

  def create
    @comment = @entry.comments.build(comment_params)

    if @comment.save
      render :nothing => true, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  def update
    if @comment.update(comment_params)
      render :nothing => true, status: :ok
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    render :nothing => true, :status => :no_content
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_entry
      @entry = Entry.find(params[:entry_id])
    end

    def comment_params
      params.require(:comment).permit(:name, :description, :post_date, :entry_id)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_entry, only: [:index, :create, :new]
  before_action :authorize, only: [:update, :destroy]


  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @entry.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @entry, notice: 'Comment was successfully created.' }
        format.js
      else
        render entry_path(id: @entry.id)
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @entry = @comment.entry
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @entry, notice: 'Comment was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_entry
      @entry = Entry.find(params[:entry_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :description, :post_date, :entry_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<h4>Add a Comment</h4>
<%= form_for([@entry, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Comment" %><br>
    <%= f.text_area :description, rows: "5" %>
  </div>
  <div class="actions">
    <%= f.submit("New Comment") %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#new-comment-modal").html('').foundation("reveal", "close");

$("#show-entry").html('<%= j render entry_path %>');

app/views/comments/destroy.js.erb
$('#<%= dom_id @comment %>').fadeOut();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$("#new-comment-modal").html('<%= j render "comments/form" %>').
  append('<a class="close-reveal-modal">&#215;</a>').
  foundation("reveal", "open");

$("#new_entry_comment").attr("data-remote", "true");

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @comment.name %></p>
<p><%= markdown @comment.description %></p>
<p><%= @comment.post_date %></p>
<p>entry_id: <%= @comment.entry_id %></p>