config/routes.rb
Rails.application.routes.draw do

  get 'sign_up' => 'users#new', :as => 'sign_up'
  get "users/:id" => "users#show", as: "user_show"
  get "users/:id/api_token" => "users#api_token", as: "user_api_token"
  resources :users

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: [:new, :create, :destroy]

  resources :entries do
    resources :comments, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1, path: "" do
      resources :users, except: [:new, :edit]
      resources :entries, except: [:index, :new, :edit] do
        resources :comments, shallow: true
      end
    end
  end

  get 'home/index'

  root 'home#index'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  before_create :set_date

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 1, maximum: 50 }
  validates :description, presence: true, length: { minimum: 1 }
  #validate :title_unique

  def set_date
    self.post_date = Time.now
  end

  # Add authentication
  # def title_unique
  #   Entry.where(user_id: current_user.id).pluck(:title).each do |entry_title|
  #     if title == entry_title
  #       errors.add(:title, "Title used previously. Choose another Title")
  #     end
  #   end
  # end
end

app/controllers/api/v1/entries_controller.rb
class API::V1::EntriesController < API::V1::BaseController
  before_action :set_entry, only: [:show, :update, :destroy]
  before_action :set_entry_comments, only: [:show]
  before_action only: [:update, :destroy] do
    authorize(:entry, @entry.id)
  end
  before_action only: :create do
    authorize(:user, nil)
  end

  def show
  end

  def create
    user = User.find_by_api_token(params[:api_token])
    @entry = user.entries.build(entry_params)

    if @entry.save
      render :nothing, status: :created
    else
      render json: @entry.errors, status: :unprocessable_entity
    end
  end

  def update
    if @entry.update(entry_params)
      render :nothing, status: :ok
    else
      render json: @entry.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @entry.destroy
    render :nothing => true, :status => :no_content
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:title, :description, :post_date, :user_id)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :set_entry_comments, only: [:show]
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]

  def index
    @entries = Entry.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = current_user.entries.build(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = @entry.user
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Entry was successfully destroyed.' }
    end
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def set_user
    @user = User.find(current_user.id) if current_user
  end

  def entry_params
    params.require(:entry).permit(:title, :description, :post_date, :user_id)
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<div class="panel small-6 small-centered columns">
<h1>Edit Post</h1>
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Article" %><br>
    <%= f.text_area :description, rows: 18 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">

    <li class="name">
      <h1>
        <%= link_to "WeBe Bloggin", "/", class: "webe" %>
      </h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>

    <section class="top-bar-section">

      <ul class="right">
        <li class="divider"></li>
        <li class="events"><%= link_to "Post", entry_path(id: @entry.id) %></li>
        <li class="divider"></li>
        <li class="events"><%= link_to "Blog", user_path(id: @user.id) %></li>
        <li class="divider"></li>
        <li class="events"><%= link_to "Log out", log_out_path %></li>
        <li class="divider"></li>
      </ul>
    </section>
</nav>

<%= render 'form' %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.post_date %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<div id="show-entry">
  <% unless current_user == nil %>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">

        <li class="name">
          <h1>
            <%= link_to "WeBe Bloggin", "/", class: "webe" %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>

        <section class="top-bar-section">

          <ul class="right">
            <li class="divider"></li>
            <li class="events"><%= link_to 'Delete Post', @entry, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            <li class="divider"></li>
            <li class="events"><%= link_to "Edit Post", edit_entry_path %></li>
            <li class="divider"></li>
            <li class="events"><%= link_to "Create Post", users_path %></li>
            <li class="divider"></li>
            <li class="events"><%= link_to "Blog", user_path(id: @user.id) %></li>
            <li class="divider"></li>
            <li class="events"><%= link_to "Log out", log_out_path %></li>
            <li class="divider"></li>
          </ul>
        </section>
    </nav>
  <% else %>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">

        <li class="name">
          <h1>
            <%= link_to "WeBe Bloggin", "/", class: "webe" %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>

        <section class="top-bar-section">

          <ul class="right">
            <li class="divider"></li>
            <li class="divider"></li>
          </ul>
        </section>
    </nav>
  <% end %>

  <div class="panel small-6 small-centered columns">
  <h2><%= @entry.title %></h2>
  <p><%= markdown @entry.description %></p>
  <p><%= @entry.post_date %></p><br><p class="style"></p><br>

  <h3 class="white-text">
    <%= link_to "Add a Comment", new_entry_comment_path(entry_id: @entry.id),
        "data-reveal-id" => "new-comment-modal",  remote: true,
        class: "button [radius round small large]" %>
  </h3>

  <% @entry_comments.each do |comment| %>
    <div id="<%= dom_id comment %>">
      <br><br><h5><%= comment.name %></h5>
      <p><%= markdown comment.description %></p>
      <p><%= comment.post_date %></p><br><p class="style"></p>
      <% unless current_user == nil %>
        <p><%= link_to 'Delete comment', comment, remote: true,
                        method: :delete,
                        class: "white-text" %>
        </p>
    </div>
    <% end %>
  <% end %>

  <%= paginate @entry_comments %>

  </div>
</div>
<div id="new-comment-modal" class="reveal-modal" data-reveal></div>