config/routes.rb
Rails.application.routes.draw do

  get 'sign_up' => 'users#new', :as => 'sign_up'
  get "users/:id" => "users#show", as: "user_show"
  get "users/:id/api_token" => "users#api_token", as: "user_api_token"
  resources :users

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: [:new, :create, :destroy]

  resources :entries do
    resources :comments, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1, path: "" do
      resources :users, except: [:new, :edit]
      resources :entries, except: [:index, :new, :edit] do
        resources :comments, shallow: true
      end
    end
  end

  get 'home/index'

  root 'home#index'
end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  before_save :set_api_token

  has_many :entries,  dependent: :destroy

  validates :password, presence: true, :length => { minimum: 6, maximum: 20 },
                       confirmation: true
  validates :username, presence: true, :uniqueness => true

  def self.authenticate(username, password)
    user = find_by username: username
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def set_api_token
    # begin while statement checks whether the generated api token already exists.
    # If the token does exist it generates a new one until a unique one is created.
    begin
      self.api_token = SecureRandom.urlsafe_base64
    end while User.exists?(api_token: api_token)
  end
end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < API::V1::BaseController
  before_action :set_user, only: [:show, :update, :destroy]
  before_action only: [:update, :destroy] do
    authorize(:user, nil)
  end

  def index
    @users = User.all.page(params[:page]).per(50)
  end

  def show
    @entries = Entry.where(user_id: @user.id).order(post_date: :desc).page(params[:page]).per(10)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      render :nothing, status: :created
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      render :nothing, status: :ok
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    render :nothing => true, :status => :no_content
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :api_token, :edit, :update, :destroy]
  before_action :authorize, only: [:index, :edit, :update]

  def index
    @user = User.find(current_user.id) if current_user
    @entry = Entry.new
  end

  def show
    @user = User.find(current_user.id) if current_user
    @entries = Entry.where(user_id: @user.id).order(post_date: :desc).page(params[:page]).per(7)
  end

  def api_token
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to log_in_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_sign_up.html.erb
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit("Sign up") %>
  </div>
<% end %>

app/views/users/api_token.html.erb
<br><br><br><div class="panel small-6 small-centered columns">
  <p><%= "API token: #{@user.api_token}" %></p>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% unless current_user == nil %>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">

      <li class="name">
        <h1>
          <%= link_to "WeBe Bloggin", "/", class: "webe" %>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>

      <section class="top-bar-section">

        <ul class="right">
          <li class="divider"></li>
          <li class="events"><%= link_to "API Token", user_api_token_path(id: @user.id) %></li>
          <li class="divider"></li>
          <li class="events"><%= link_to "Blog", user_path(id: @user.id) %></li>
          <li class="divider"></li>
          <li class="events"><%= link_to "Log out", log_out_path %></li>
          <li class="divider"></li>
        </ul>
      </section>
  </nav>

  <div class="panel small-6 small-centered columns">
  <h1>Post</h1>
  <%= form_for(@entry) do |f| %>
    <% if @entry.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

        <ul>
        <% @entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label "Article" %><br>
      <%= f.text_area :description, rows: "18" %>
    </div>
    <div class="actions">
      <%= f.submit("New") %>
    </div>
  <% end %>
  </div>
<% else %>
  <h1 class="white-text">You must be logged in to view this page.</h1>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% unless current_user == nil %>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">

      <li class="name">
        <h1>
          <%= link_to "WeBe Bloggin", "/", class: "webe" %>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>

      <section class="top-bar-section">

        <ul class="right">
          <li class="divider"></li>
          <li class="events"><%= link_to "Create Post", users_path %></li>
          <li class="divider"></li>
          <li class="events"><%= link_to "Log out", log_out_path %></li>
          <li class="divider"></li>
        </ul>
      </section>
  </nav>
<% else %>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">

      <li class="name">
        <h1>
          <%= link_to "WeBe Bloggin", "/", class: "webe" %>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>

      <section class="top-bar-section">

        <ul class="right">
          <li class="divider"></li>
          <li class="divider"></li>
        </ul>
      </section>
  </nav>
<% end %>

<div class="panel small-9 small-centered columns">
  <div class='row'>
    <h1>Recent Posts</h1><br><br>
    <% @entries.each do |entry| %>
      <h3><%= link_to entry.title, entry_path(id: entry.id), class: "white-text" %></h3>
      <p><%= markdown entry.description %></p>
      <p><%= entry.post_date %></p><br><p class="style"></p><br>
    <% end %>
  </div>
  <p id="notice"><%= notice %></p>
    <%= paginate @entries %>
</div>