config/routes.rb
Rails.application.routes.draw do

  get 'sign_up' => 'users#new', :as => 'sign_up'
  get "users/:id" => "users#show", as: "user_show"
  get "users/:id/api_token" => "users#api_token", as: "user_api_token"
  resources :users

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: [:new, :create, :destroy]

  resources :entries do
    resources :comments, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1, path: "" do
      resources :users, except: [:new, :edit]
      resources :entries, except: [:index, :new, :edit] do
        resources :comments, shallow: true
      end
    end
  end

  get 'home/index'

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">

    <li class="name">
      <h1>
        <%= link_to "WeBe Bloggin", "/", class: "webe" %>
      </h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>

    <section class="top-bar-section">

      <ul class="right">
        <li class="divider"></li>
        <li class="events"><%= link_to "Log In", log_in_path %></li>
        <li class="divider"></li>
      </ul>
    </section>
</nav>

app/views/home/index.html.erb
<% logged_in_redirect %>

<%= render "nav" %>


<div class="panel small-4 small-centered columns">
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit("Sign up") %>
  </div>
<% end %>
</div>